[package]
name = "nephrite4-cli"
version = "0.1.0"
authors = ["Yu Changyuan <reivzy@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
nephrite4-common = { path = "../common" }

dotenv = "0.15"
log = "0.4"
env_logger = "0.8.3"
